### ISSUE TITLE
polish off gui and architecture (option windows mainly)

### ISSUE THREAD

**Issue by mk306** [CustomComputingGroup/MLO#21]
1.graph specification mechanism should be updated to include different visualizers for different trial types ( not used currently)
2.add possibility in options to change graph generation range. Regenerating images within a range of the main iterator ( generations usually).

**Comment by icltc** [comment]
Cool!!
Have you update the code??
I saw the gui is run separately by Mac OS and None-Mac, have you change both?? Because I found there is no image showing in my run in the Mac OS. 
I also found this, are the trial names suppose to be what I input as the run name??
![image](https://f.cloud.github.com/assets/3298542/123811/4e4e4ade-6ed8-11e2-911a-d5ffebb81ffa.png)

**Comment by mk306** [comment]
they should be unique - thats it. You can change the naming convention if you need to (I dont mind). 

"I saw the gui is run separately by Mac OS and None-Mac, have you change both?" - what do you mean? The visualizer is different (Mac OS uses SingleThreadVisualizer) cause apparently there were some issues with using multiple threads for visualization under Mac OS. I updated the class so it should work now, Ill include it in a new commit before 6 today.
